=== Unidata/tds/tds/src/main/resources/schema/wmsConfig_2_0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT wmsConfig (global, overrides?)>

<!ELEMENT global (defaults, standardNames?)>

<!ELEMENT defaults (allowFeatureInfo, defaultColorScaleRange, defaultAboveMaxColor, defaultBelowMinColor, defaultNoDataColor, defaultOpacity, defaultPaletteName, defaultNumColorBands, logScaling, intervalTime)>

<!ELEMENT standardNames (standardName*)>

<!ELEMENT standardName (defaultColorScaleRange?, defaultAboveMaxColor?, defaultBelowMinColor?, defaultNoDataColor?, defaultOpacity?, defaultPaletteName?, defaultNumColorBands?, logScaling?, intervalTime?)>
<!ATTLIST standardName name CDATA #REQUIRED>
<!ATTLIST standardName units CDATA #REQUIRED>

<!ELEMENT overrides (datasetPath*)>

<!ELEMENT datasetPath (pathDefaults?, variables?)>
<!ATTLIST datasetPath pathSpec CDATA #REQUIRED>

<!ELEMENT pathDefaults (allowFeatureInfo?, defaultColorScaleRange?, defaultAboveMaxColor?, defaultBelowMinColor?, defaultNoDataColor?, defaultOpacity?, defaultPaletteName?, defaultNumColorBands?, logScaling?, intervalTime?)>

<!ELEMENT variables (variable*)>

<!ELEMENT variable (defaultColorScaleRange?, defaultAboveMaxColor?, defaultAboveMaxColor?, defaultBelowMinColor?, defaultNoDataColor?, defaultOpacity?, defaultPaletteName?, defaultNumColorBands?, logScaling?, intervalTime?)>
<!ATTLIST variable id CDATA #REQUIRED>

<!ELEMENT allowFeatureInfo (#PCDATA)>
<!ELEMENT defaultColorScaleRange (#PCDATA)>
<!ELEMENT defaultAboveMaxColor (#PCDATA)>
<!ELEMENT defaultBelowMinColor (#PCDATA)>
<!ELEMENT defaultNoDataColor (#PCDATA)>
<!ELEMENT defaultOpacity  (#PCDATA)>
<!ELEMENT defaultPaletteName (#PCDATA)>
<!ELEMENT defaultNumColorBands (#PCDATA)>
<!ELEMENT logScaling (#PCDATA)>
<!ELEMENT intervalTime (#PCDATA)> <!-- Allows to use time ranges instead of lists in the capabilities documents -->

=== Unidata/tds/tds/src/main/webapp/WEB-INF/altContent/startup/wmsConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wmsConfig SYSTEM "https://schemas.unidata.ucar.edu/thredds/dtd/ncwms/wmsConfig_2_0.dtd">
<!--
Detailed configuration of the WMS service.  This config file can be used to
set default styling parameters for each dataset/variable, and to enable or disable
the GetFeatureInfo operation.
-->
<wmsConfig>
    <global>
        <!-- These settings apply to all datasets unless overridden below -->
        <defaults>
            <!-- The global defaults. All elements are mandatory -->
            <allowFeatureInfo>true</allowFeatureInfo>
            <defaultColorScaleRange>-50 50</defaultColorScaleRange>
            <defaultAboveMaxColor>#000000</defaultAboveMaxColor>
            <defaultBelowMinColor>#000000</defaultBelowMinColor>
            <defaultNoDataColor>extend</defaultNoDataColor>
            <defaultOpacity>100</defaultOpacity>
            <defaultPaletteName>psu-viridis</defaultPaletteName>
            <defaultNumColorBands>20</defaultNumColorBands>
            <logScaling>false</logScaling>
            <!--Deprecated: intervalTime (does not work, to be removed in v6)-->
            <intervalTime>false</intervalTime>
        </defaults>
        <standardNames>
            <!-- Use this section to set defaults per standard name -->
            <!-- Units must come from the UDUNITS vocabulary -->
            <standardName name="sea_water_potential_temperature" units="K">
                <defaultColorScaleRange>268 308</defaultColorScaleRange>
            </standardName>
            <standardName name="sea_water_temperature" units="K">
                <defaultColorScaleRange>268 308</defaultColorScaleRange>
            </standardName>
            <standardName name="mass_concentration_of_chlorophyll_in_sea_water" units="kg m-3">
                <logScaling>true</logScaling>
            </standardName>
        </standardNames>
    </global>
    <overrides>
        <datasetPath pathSpec="testAll/20040503*_eta_211.nc">
            <!-- Will apply to all paths that match the path spec above -->
            <pathDefaults>
                <!-- These will apply to all variables in this path unless overridden below -->
                <allowFeatureInfo>false</allowFeatureInfo>
                <defaultPaletteName>x-Occam</defaultPaletteName>
            </pathDefaults>

            <variables>
                <!-- Configure variables individually according to their internal ID.
                     This is the most specific setting and will override any others -->
                <variable id="Z_sfc">
                    <defaultColorScaleRange>0 2920</defaultColorScaleRange>
                    <defaultAboveMaxColor>extend</defaultAboveMaxColor>
                    <defaultBelowMinColor>#0000ff</defaultBelowMinColor>
                    <defaultNoDataColor>transparent</defaultNoDataColor>
                    <defaultOpacity>95</defaultOpacity>
                </variable>
            </variables>
        </datasetPath>
        <datasetPath pathSpec="testAll/20040504*_eta_211.nc">
            <!-- Will apply to all paths that match the path spec above -->
            <pathDefaults>
                <!-- These will apply to all variables in this path unless overridden below -->
                <allowFeatureInfo>true</allowFeatureInfo>
                <defaultPaletteName>seq-Reds</defaultPaletteName>
            </pathDefaults>
            <variables>
                <!-- Configure variables individually according to their internal ID.
                     This is the most specific setting and will override any others -->
                <variable id="Z_sfc">
                    <defaultColorScaleRange>0 3170</defaultColorScaleRange>
                </variable>
            </variables>
        </datasetPath>
    </overrides>
</wmsConfig>
